services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petcare_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    image: petcare-api
    container_name: petcare_api
    build:
      context: .
      dockerfile: PetCare.Api/Dockerfile
    ports:
      - "5084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  webapp:
    image: petcare-webapp
    container_name: petcare_webapp
    build:
      context: .
      dockerfile: PetCare.WebApp/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api

volumes:
  sqlvolume: